version: '2'
services:
  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    environment:
      - STORAGE_TYPE=elasticsearch
      - ES_HOSTS=192.168.1.61:9200
      - RABBIT_ADDRESSES=192.168.1.61:5672
      - RABBIT_USER=admin 
      - RABBIT_PASSWORD=admin
    ports:
      # Port used for the Zipkin UI and HTTP Api
      - 9411:9411